### PR TITLE
Create essentials.md

### PR DESCRIPTION
**Pull request by LuisArteaga**
New resources for python essentials.

### CODE REVIEW

**Comment by ovv** [comment]
Awesome !

I thing providing feedback on the books and/or idea & topics it focus on could be a nice improvements than just listing them

**Comment by mikefromit** [comment]
You need to create your PR on a new branch.

**Comment by ovv** [comment]
You should also add a link from the readme to the essentials

**Comment by mikefromit** [comment]
@ovv, i definitely agree. a summary as to why a particular resource is good would be helpful. maybe even a pro/con table. one thing at a time 😉

**Comment by mikefromit** [comment]
Ah yea, good catch. @LuisArteaga plz add essentials to the readme.md

**Comment by LuisArteaga** [comment]
Thanks Quentin & Mike for your feedback.

@ovv - you are right. A comment or a quick overview of each book would be very helpful for other members. I will add them very soon. 

@mikefromit  - a pro/con table is a good idea. I would like to add them later, after reviewing my progress Then I will have a better understanding of which books really lead to my growth. 

@all
1.) I am going to create a branch and pull a request again. Let's do it right :).
2.) I will change the readme file.

**Comment by m1yag1** [comment]
sounds good, looking forward to checking it out.

**Comment by mikefromit** [comment]
sounds good, looking forward to checking it out 😉

**Pull request closed without merging**
